apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: giridharazurevotingappredis 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: giridharazurevotingappredis 
    spec:
      containers:
        - name: giridharazurevotingappredis 
          image: ensiteacr.azurecr.io/giridharazurevotingappredis
          ports:
          - containerPort: 80